runtime: python39

instance_class: F2

env_variables:
  FLASK_ENV: "production"
  JWT_EXPIRATION_SECONDS: "3600"
  # Don't include sensitive values like JWT_SECRET_KEY here
  # Set them through the GCP Console or gcloud command

# Use gunicorn as the production server
entrypoint: gunicorn -b :$PORT app:app

# Configure this to true if you want to restrict access
# to only authenticated users
handlers:
- url: /health
  script: auto
  secure: always

- url: /login
  script: auto
  secure: always

- url: /.*
  script: auto
  secure: always
  login: required 